---
abstract: 'Building, finding and using tidyp library - L<http://www.tidyp.com>'
author:
  - 'KMX, kmx@cpan.org'
build_requires:
  Archive::Extract: 0
  Digest::SHA: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Command: 0
  ExtUtils::Liblist: 0
  File::Fetch: 0
  File::Path: 0
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
  perl: 5.008
configure_requires:
  Archive::Extract: 0
  Digest::SHA: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Command: 0
  ExtUtils::Liblist: 0
  File::Fetch: 0
  File::Path: 0
  File::ShareDir: 0
  File::Spec: 0
  File::Temp: 0
  Module::Build: 0.36
  perl: 5.008
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-Tidyp
provides:
  Alien::Tidyp:
    file: lib/Alien/Tidyp.pm
    version: v1.4.2
requires:
  File::ShareDir: 1.00
  File::Spec: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-Tidyp
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kmx/alien-tidyp
version: v1.4.2
