---
abstract: 'Build and make available tidyp library - L<http://www.tidyp.com>'
author:
  - 'KMX, kmx@cpan.org'
build_requires:
  ExtUtils::Command: 0
  File::ShareDir: 0
  File::Spec: 0
  Test::More: 0
configure_requires:
  ExtUtils::Command: 0
  File::Spec: 0
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-Tidyp
no_index:
  directory:
    - src
provides:
  Alien::Tidyp:
    file: lib/Alien/Tidyp.pm
    version: v0.99.7
requires:
  File::ShareDir: 1.00
  File::Spec: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-Tidyp
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kmx/alien-tidyp
version: v0.99.7
